name = "dog-walking-ui"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./build"
entry-point = "."

[env.production]
name = "dog-walking-ui-prod"
route = ""

[env.staging]
name = "dog-walking-ui-staging"
route = ""